exclude: |
  (?x)^(
    vendor/.*
  )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: |
      (?x)^(
        cicd/deploy/charts/.*?/templates/.*|
        testdata/charts/.*?/templates/.*
      )$
    args:
    - --allow-multiple-documents
